development:
  GOOGLE_API_KEY: "AIzaSyA5fgcdiQETqVww3Mb9lH6Endu_9XWyAyU"
  GOOGLE_CUSTOM_SEARCH_ENGINE_KEY: "014532163075185725574:_hkfc83wdlk"

test:
  GOOGLE_API_KEY: "AIzaSyA5fgcdiQETqVww3Mb9lH6Endu_9XWyAyU"
  GOOGLE_CUSTOM_SEARCH_ENGINE_KEY: "014532163075185725574:_hkfc83wdlk"
