development:
  GOOGLE_API_KEY: "AIzaSyCg3FHgcAg7-2kRuSSg2za9eOjuJ7cCy9Q"
  GOOGLE_CUSTOM_SEARCH_ENGINE_KEY: "008720231582236854502:xxfh1sasv0o"

test:
  GOOGLE_API_KEY: "AIzaSyA5fgcdiQETqVww3Mb9lH6Endu_9XWyAyU"
  GOOGLE_CUSTOM_SEARCH_ENGINE_KEY: "014532163075185725574:_hkfc83wdlk"
